version: '3'

services: 
    web:
        image: drupal:latest
        ports:
          - 8080:80
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles       
            - drupal-sites:/var/www/html/sites      
            - drupal-themes:/var/www/html/themes
      
    database:
        image: postgres:13-alpine
        environment:
          POSTGRES_PASSWORD: 1111

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: