# create your drupal and postgres config here, based off the last assignment

version: '3'

services: 
    web:
        build: 
            context: .
            dockerfile: drupal.Dockerfile
        image: custom-drupal
        ports:
          - 8080:80
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles       
            - drupal-sites:/var/www/html/sites      
            - drupal-themes:/var/www/html/themes
            - drupal-data:/var/lib/postgresql/data
      
    database:
        image: postgres:12.1
        environment:
          POSTGRES_PASSWORD: 1111

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
