# create your drupal and postgres config here, based off the last assignment
# assignment - create stack with secrets - based on previous file

version: '3.1'

services: 
    web:
        image: drupal:8.2
        ports:
          - 8080:80
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles       
            - drupal-sites:/var/www/html/sites      
            - drupal-themes:/var/www/html/themes
            - drupal-data:/var/lib/postgresql/data
      
    database:
        image: postgres:12.1
        secrets:
         - psql_pw
        environment:
         - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pw


secrets:
  psql_pw:
    external: true

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
